environment:
  GITHUB_TOKEN:
    secure: E1HpiZf9OJuc8XPGA57hJbCQlMWVCPVBePHiWF/BgmJ/+e/2OplyifiS/x8CJtcw
  matrix:
    - rebuild_for: "1.4.10"
      electron: "1.4.10"
    - rebuild_for: "1.4.10"
      electron: "1.4.8"
    - rebuild_for: "1.4.10"
      electron: "1.4.7"
    - rebuild_for: "1.4.10"
      electron: "1.4.6"
    - rebuild_for: "1.4.10"
      electron: "1.4.5"
    - rebuild_for: "1.4.10"
      electron: "1.4.4"
    - rebuild_for: "1.4.10"
      electron: "1.4.3"
    - rebuild_for: "1.4.10"
      electron: "1.4.2"
    - rebuild_for: "1.4.10"
      electron: "1.4.1"
    - rebuild_for: "1.4.10"
      electron: "1.4.0"
    - rebuild_for: "1.3.12"
      electron: "1.3.12"
    - rebuild_for: "1.3.12"
      electron: "1.3.10"
    - rebuild_for: "1.3.12"
      electron: "1.3.9"
    - rebuild_for: "1.3.12"
      electron: "1.3.8"
    - rebuild_for: "1.3.12"
      electron: "1.3.7"
    - rebuild_for: "1.3.12"
      electron: "1.3.6"
    - rebuild_for: "1.3.12"
      electron: "1.3.5"
    - rebuild_for: "1.3.12"
      electron: "1.3.4"
    - rebuild_for: "1.3.12"
      electron: "1.3.3"
    - rebuild_for: "1.3.12"
      electron: "1.3.2"
    - rebuild_for: "1.3.12"
      electron: "1.3.1"
    - rebuild_for: "1.3.12"
      electron: "1.3.0"
    - rebuild_for: "1.2.8"
      electron: "1.2.8"
    - rebuild_for: "1.2.8"
      electron: "1.2.7"
    - rebuild_for: "1.2.8"
      electron: "1.2.6"
    - rebuild_for: "1.2.8"
      electron: "1.2.5"
    - rebuild_for: "1.2.8"
      electron: "1.2.4"
    - rebuild_for: "1.2.8"
      electron: "1.2.3"
    - rebuild_for: "1.2.8"
      electron: "1.2.2"
    - rebuild_for: "1.2.8"
      electron: "1.2.1"
    - rebuild_for: "1.2.8"
      electron: "1.2.0"
    - rebuild_for: "1.2.8"
      electron: "1.1.3"
    - rebuild_for: "1.2.8"
      electron: "1.1.2"
    - rebuild_for: "1.2.8"
      electron: "1.1.1"
    - rebuild_for: "1.2.8"
      electron: "1.1.0"
    - rebuild_for: "1.0.2"
      electron: "1.0.2"
    - rebuild_for: "1.0.2"
      electron: "1.0.1"
    - rebuild_for: "1.0.2"
      electron: "1.0.0"
    - rebuild_for: "1.0.2"
      electron: "0.37.8"
    - rebuild_for: "1.0.2"
      electron: "0.37.7"
    - rebuild_for: "1.0.2"
      electron: "0.37.6"
    - rebuild_for: "1.0.2"
      electron: "0.37.5"
    - rebuild_for: "1.0.2"
      electron: "0.37.4"
    - rebuild_for: "1.0.2"
      electron: "0.37.3"
    - rebuild_for: "1.0.2"
      electron: "0.37.2"
    - rebuild_for: "1.0.2"
      electron: "0.37.1"
    - rebuild_for: "1.0.2"
      electron: "0.37.0"
    - rebuild_for: "1.0.2"
      electron: "0.36.12"
    - rebuild_for: "1.0.2"
      electron: "0.36.11"
    - rebuild_for: "1.0.2"
      electron: "0.36.10"
    - rebuild_for: "1.0.2"
      electron: "0.36.9"
    - rebuild_for: "1.0.2"
      electron: "0.36.8"
    - rebuild_for: "1.0.2"
      electron: "0.36.7"
    - rebuild_for: "1.0.2"
      electron: "0.36.6"
    - rebuild_for: "1.0.2"
      electron: "0.36.5"
    - rebuild_for: "1.0.2"
      electron: "0.36.4"
    - rebuild_for: "1.0.2"
      electron: "0.36.3"
    - rebuild_for: "1.0.2"
      electron: "0.36.2"
    - rebuild_for: "1.0.2"
      electron: "0.36.1"
    - rebuild_for: "1.0.2"
      electron: "0.36.0"
    - rebuild_for: "0.35.6"
      electron: "0.35.6"
    - rebuild_for: "0.35.6"
      electron: "0.35.5"
    - rebuild_for: "0.35.6"
      electron: "0.35.4"
    - rebuild_for: "0.35.6"
      electron: "0.35.3"
    - rebuild_for: "0.35.6"
      electron: "0.35.2"
    - rebuild_for: "0.35.6"
      electron: "0.35.1"
    - rebuild_for: "0.35.6"
      electron: "0.35.0"
    - rebuild_for: "0.35.6"
      electron: "0.34.5"
    - rebuild_for: "0.35.6"
      electron: "0.34.4"
    - rebuild_for: "0.35.6"
      electron: "0.34.3"
    - rebuild_for: "0.35.6"
      electron: "0.34.2"
    - rebuild_for: "0.35.6"
      electron: "0.34.1"
    - rebuild_for: "0.35.6"
      electron: "0.34.0"
    - rebuild_for: "0.35.6"
      electron: "0.33.9"
    - rebuild_for: "0.35.6"
      electron: "0.33.8"
    - rebuild_for: "0.35.6"
      electron: "0.33.7"
    - rebuild_for: "0.35.6"
      electron: "0.33.6"
    - rebuild_for: "0.35.6"
      electron: "0.33.5"
    - rebuild_for: "0.35.6"
      electron: "0.33.4"
    - rebuild_for: "0.35.6"
      electron: "0.33.3"
    - rebuild_for: "0.35.6"
      electron: "0.33.2"
    - rebuild_for: "0.35.6"
      electron: "0.33.1"
    - rebuild_for: "0.35.6"
      electron: "0.33.0"
    - rebuild_for: "0.32.3"
      electron: "0.32.3"
    - rebuild_for: "0.32.3"
      electron: "0.32.2"
    - rebuild_for: "0.32.3"
      electron: "0.32.1"
    - rebuild_for: "0.32.3"
      electron: "0.32.0"
    - rebuild_for: "0.32.3"
      electron: "0.31.2"
    - rebuild_for: "0.32.3"
      electron: "0.31.1"
    - rebuild_for: "0.32.3"
      electron: "0.31.0"
    - rebuild_for: "0.30.8"
      electron: "0.30.8"
    - rebuild_for: "0.30.8"
      electron: "0.30.7"
    - rebuild_for: "0.30.8"
      electron: "0.30.6"
    - rebuild_for: "0.30.8"
      electron: "0.30.5"
    - rebuild_for: "0.30.8"
      electron: "0.30.4"
    - rebuild_for: "0.30.8"
      electron: "0.30.3"
    - rebuild_for: "0.30.8"
      electron: "0.30.2"
    - rebuild_for: "0.30.8"
      electron: "0.30.1"
    - rebuild_for: "0.30.8"
      electron: "0.30.0"


platform:
  - x64

build: off

install:
  - ps: Install-Product node 6 $env:platform
  - npm install electron@%ELECTRON%
  - npm install --runtime=electron --target=%REBUILD_FOR% --disturl=https://atom.io/download/electron


test_script:
  - npm run test:electron
